### ISSUE TITLE
повторення фону

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-22-DOM-2#1]
https://github.com/BohdanLuts/home-work-lesson-22-DOM-2/blob/f11400021bd2736bc25119572556408f521e22e3/js/index.js#L53
- составна властивість background перезатираэ всі часткові властивості, прописані в класі. Тут треба задати конкретніше backgroundImage

**Comment by BohdanLuts** [comment]
Замінив, запрацювало.

Прийму до уваги.
